// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB28S63JKUGCErGi5wRGM4Lr11fvtXLDgg',
    appId: '1:411945979700:web:8fb77cb3b995a504201f61',
    messagingSenderId: '411945979700',
    projectId: 'todo-app-5e168',
    authDomain: 'todo-app-5e168.firebaseapp.com',
    storageBucket: 'todo-app-5e168.firebasestorage.app',
    measurementId: 'G-G4241DDHJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-V6-Fu67-bzrSaPkgsKVEaxZGkg7oAF4',
    appId: '1:411945979700:android:84261aa53832163f201f61',
    messagingSenderId: '411945979700',
    projectId: 'todo-app-5e168',
    storageBucket: 'todo-app-5e168.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADvio7gj-yMLQuKckrGMySHoaMGPeXT9g',
    appId: '1:411945979700:ios:9ff7776ed773954d201f61',
    messagingSenderId: '411945979700',
    projectId: 'todo-app-5e168',
    storageBucket: 'todo-app-5e168.firebasestorage.app',
    iosBundleId: 'com.example.itiFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADvio7gj-yMLQuKckrGMySHoaMGPeXT9g',
    appId: '1:411945979700:ios:9ff7776ed773954d201f61',
    messagingSenderId: '411945979700',
    projectId: 'todo-app-5e168',
    storageBucket: 'todo-app-5e168.firebasestorage.app',
    iosBundleId: 'com.example.itiFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB28S63JKUGCErGi5wRGM4Lr11fvtXLDgg',
    appId: '1:411945979700:web:6cc889b0c2f47e57201f61',
    messagingSenderId: '411945979700',
    projectId: 'todo-app-5e168',
    authDomain: 'todo-app-5e168.firebaseapp.com',
    storageBucket: 'todo-app-5e168.firebasestorage.app',
    measurementId: 'G-LET8MPMS8X',
  );
}
